definitions:
  api.home:
    properties:
      title:
        type: string
    type: object
  helpers.BaseResponse:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
  models.User:
    properties:
      address:
        type: string
      dob:
        type: string
      email:
        type: string
      full_name:
        type: string
      id:
        type: integer
      password:
        type: string
      phone_number:
        type: string
      role:
        type: string
      username:
        type: string
    required:
    - email
    - full_name
    - password
    - phone_number
    - username
    type: object
info:
  contact: {}
paths:
  /api/v1/auth/register:
    post:
      consumes:
      - application/json
      description: Register a new customer user account
      parameters:
      - description: User registration details
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully registered user
          schema:
            $ref: '#/definitions/helpers.BaseResponse'
        "400":
          description: Bad request - invalid input
          schema:
            $ref: '#/definitions/helpers.BaseResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/helpers.BaseResponse'
      summary: Register a new user
      tags:
      - users
  /health:
    get:
      consumes:
      - application/json
      description: Check if the service is running
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.home'
      summary: Health check endpoint
      tags:
      - health
swagger: "2.0"
